In [3]:
import numpy as np

Задание 1

In [5]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Задание 2

In [6]:
b = a.reshape(2,6)
b

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [7]:
c = a.reshape(4,3)
c

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [9]:
d = a.reshape(6,2)
d

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [10]:
e = a.reshape(3,4)
e

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
f = a.reshape(12,1)
f

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Задание 3

In [14]:
g = a.reshape(3,-1)
g

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
h = a.reshape(4,-1)
h

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [16]:
i = a.reshape(2,-1)
i

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [20]:
j = a.reshape(-1,2)
j

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [21]:
k = a.reshape(-1,6)
k

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

Задание 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [26]:
Нет,нельзя.

Задание 5

In [30]:
b=np.random.randn(3,4)
b


array([[-1.07673832, -0.66821081,  1.00474673,  0.22812323],
       [ 1.27967872, -0.02266633, -0.99054146, -0.03993307],
       [ 0.55272088,  0.7250362 ,  0.04294512,  0.89151404]])

In [33]:
print(b.size)
b=b.flatten()
print(b.size)
b

12
12


array([-1.07673832, -0.66821081,  1.00474673,  0.22812323,  1.27967872,
       -0.02266633, -0.99054146, -0.03993307,  0.55272088,  0.7250362 ,
        0.04294512,  0.89151404])

Задание 6

In [35]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Задание 7

In [36]:
b = np.arange(20,0,-2).reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

#В чем разница между массивами a и b?
#Разница между массивами a и b в том, что a - одномерный, а b - двумерный

Задание 8

In [38]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [43]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
v = np.vstack((a,b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [45]:
v.size

10

Задание 9

In [47]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [51]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [52]:
B.shape

(4, 4)

In [54]:
np.linalg.inv(B)

LinAlgError: Singular matrix

#Вычислить обратную матрицу для матрицы B не получится, т.к. это вырожденная (сингулярная)

Задание 10

In [57]:
np.random.seed(42)

Задание 11

In [64]:
c = np.random.randint(0,16,16)
c

array([ 9,  5, 12, 11,  8,  0, 10, 10, 14,  9, 15, 11, 11, 15, 14, 13])

Задание 12

In [69]:
C = c.reshape(4,4)
C

array([[ 9,  5, 12, 11],
       [ 8,  0, 10, 10],
       [14,  9, 15, 11],
       [11, 15, 14, 13]])

In [70]:
D = B+C*10
D

array([[ 95,  64, 143, 142],
       [ 94,  50, 186, 222],
       [163, 176, 299, 322],
       [142, 272, 352, 432]])

определитель матрицы

In [76]:
np.linalg.det(D)

-6670800.000000036

ранг матрицы

In [77]:
np.linalg.matrix_rank(D)

4

обратная матрица

In [80]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.20411345, -0.01299994, -0.15029082,  0.05161   ],
       [ 0.0309618 , -0.01359357, -0.02117587,  0.01259219],
       [-0.29589854,  0.01036158,  0.24635726, -0.09168915],
       [ 0.1545152 ,  0.00438928, -0.13800144,  0.05213168]])

Задание 13

In [81]:
D_inv=np.where(D_inv<0, 0,1)
D_inv

array([[1, 0, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 1, 0],
       [1, 1, 0, 1]])

In [82]:
E=np.where(D_inv==1, B, C)
E

array([[  5,   5,  12,  32],
       [ 14,   0,  10, 122],
       [ 14,  86, 149,  11],
       [ 32, 122,  14, 302]])