In [3]:
import numpy as np

In [49]:
import pandas as pd

In [4]:
a = np.array([[1,6],
             [2,8],
             [3,11],
             [3,10],
             [1,7]])

In [5]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
a.shape

(5, 2)

In [7]:
mean_a = a.mean(axis=0)

In [8]:
mean_a

array([2. , 8.4])

Задание 2

In [9]:
a_centered = np.subtract(a,mean_a)

In [10]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [16]:
a_centered_sp = a_centered[:, 0]  @ a_centered[:, 1]

In [17]:
a_centered_sp / 4

2.0

Задание 4

In [18]:
a_t = np.transpose(a)

In [19]:
a_t

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [20]:
a_cov = np.cov(a_t)

In [51]:
a_cov

array([[1. , 2. ],
       [2. , 4.3]])